@Library('lab32') _

pipeline {
    agent any

    tools {
        maven 'maven'
    }

    environment {
        IMAGE_NAME = "mohamedelrefy20/lab31"
        K8S_DEPLOYMENT_FILE = "deployment.yml"
        PROJECT_DIR = "Jenkins/lab31"
    }

    stages {
        stage('Pipeline Stages') {
            steps {
                script {
                    def branch = env.BRANCH_NAME ?: sh(returnStdout: true, script: "git rev-parse --abbrev-ref HEAD").trim()
                    echo "🔹 Current Branch: ${branch}"
                    runUnitTests(env.PROJECT_DIR)
                    buildAPP(env.PROJECT_DIR)
                    buildDockerImage(env.IMAGE_NAME, env.BUILD_NUMBER, env.PROJECT_DIR)
                    
                    pushDockerImage(env.IMAGE_NAME, env.BUILD_NUMBER, 'Docker_Secret')
                    removeLocalImage(env.IMAGE_NAME, env.BUILD_NUMBER)
                    updateDeploymentYaml(env.PROJECT_DIR, env.K8S_DEPLOYMENT_FILE, env.IMAGE_NAME, env.BUILD_NUMBER, branch)
                    deployOnK8s(env.PROJECT_DIR, env.K8S_DEPLOYMENT_FILE, 'SA-TOKEN', 'API-SERVER', branch)
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished — cleaning workspace"
            cleanWs()
        }
        success {
            echo "✅ Deployment succeeded!"
        }
        failure {
            echo "❌ Pipeline failed — check the logs!"
        }
    }
}
