apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  namespace: ivolve
spec:
  capacity:
    storage: 1Gi
  
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/app-logs
  