pipeline {
    agent any

    environment {
        IMAGE_NAME = "mohamedelrefy20/lab30"
        K8S_DEPLOYMENT_FILE = "deployment.yml"
    }

    stages {

        stage('Run Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'Docker_Secret', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
                        docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Delete Local Image') {
            steps {
                sh "docker rmi -f ${IMAGE_NAME}:${BUILD_NUMBER}"
            }
        }

        stage('Update deployment.yaml') {
            steps {
                script {
                    sh """
                        sed -i 's|image: .*$|image: ${IMAGE_NAME}:${BUILD_NUMBER}|g' ${K8S_DEPLOYMENT_FILE}
                        echo "Updated deployment file:"
                        cat ${K8S_DEPLOYMENT_FILE}
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([
                    string(credentialsId: 'SA-TOKEN', variable: 'TOKEN'),
                    string(credentialsId: 'API-SERVER', variable: 'APISERVER')
                ]) {
                    sh '''
                        kubectl apply -f ${K8S_DEPLOYMENT_FILE}
                    '''
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished — cleaning workspace"
            cleanWs()
        }
        success {
            echo "✅ Deployment succeeded!"
        }
        failure {
            echo "❌ Pipeline failed — check the logs!"
        }
    }
}
