version: '3.9'
services:
  app-service:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 12345
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ivolve
    volumes:
      - my-sql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-sql: {}
