apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: ivolve
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXOW9ZVzFsWkdWc2NtVm1lVEl3T21KbFltOVlZbVZpYjBBeE1qTT0iCgkJfQoJfQp9