---
- name: Configure Nginx Web Server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom web page
      ansible.builtin.copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Verify Nginx is running
      ansible.builtin.command: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Print Nginx status
      ansible.builtin.debug:
        msg: "Nginx service is {{ nginx_status.stdout }} on {{ inventory_hostname }}"