---
- name: Measure SSH connection time to each host
  hosts: localhost
  gather_facts: false
  vars:
    ssh_user: ubuntu       
    ssh_port: 22
  tasks:
    - name: Build target list
      set_fact:
        targets: "{{ groups['all'] | default([]) }}"

    - name: Measure SSH connection time for each host
      vars:
        target_host: "{{ hostvars[item].ansible_host | default(item) }}"
      loop: "{{ targets }}"
      loop_control:
        label: "{{ item }}"
      shell: >
        START=$(date +%s%3N);
        ssh -o ConnectTimeout=120 -p {{ ssh_port }} {{ ssh_user }}@{{ target_host }} "true" >/dev/null 2>&1;
        END=$(date +%s%3N);
        echo $((END - START))
      register: ssh_times
      failed_when: false
      changed_when: false

    - name: Print SSH timing results
      debug:
        msg: |
          {% for result in ssh_times.results %}
          Host: {{ result.item }}
            Duration: {{ (result.stdout | int) / 1000.0 }} seconds
            Success: {{ 'yes' if result.rc == 0 else 'no' }}
          {% endfor %}
