apiVersion: v1
kind: Pod
metadata:
  name: pod3
  namespace: ivolve
spec:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "workload"
    operator: "Equal"
    value: "worker1"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
