apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ivolve
  labels:
    app: mysql
spec:
  clusterIP: None  # Headless service
  selector:
    app: mysql
  ports:
    - port: 3306
      name: mysql
